name: hummingbot-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - boto3
  - libcxx                
  - python-dotenv
  - pandas=2.2.3
  - numpy=1.26.*          
  - pandas-ta=0.3.14b0    
  - docker-py
  - pip
  - pip:
      - hummingbot
      - pandas==2.2.3
      - pandas-ta<0.4.0       
      - msgpack>=1.0.5
      - flake8
      - isort
      - pre-commit
      - logfire
      - logfire[fastapi]
      - logfire[system-metrics]
      - aiomqtt>=2.0.0
      - sqlalchemy>=2.0.0
      - asyncpg
      - psycopg2-binary
      - greenlet
      - pydantic-settings
